/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Nov 22, 2011, 9:16:20 AM
 */
package hpc;

import image.Background;
import image.ImageHelper;
import java.io.File;
import java.util.List;
import javax.swing.JTextArea;
import javax.swing.SwingWorker;

/**
 *
 * @author Darren
 */
public class MainFrame extends javax.swing.JFrame {

    ImagePanel panel;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        byte b = 2;
        int n = 3;
        System.out.println(b + n);
        panel = new ImagePanel();
        this.setVisible(true);
        this.add(panel);
        panel.setImage(ImageHelper.openAsGrayscale(new File("testing/000010.jpg")));
        pack();
        repaint();

        Background background = new Background();

        File file[] = new File[200];
        StringBuilder builder = new StringBuilder();

        for (int i = 0; i < 200; i++) {
            builder.delete(0, builder.length());
            String numberStr = Integer.toString(i + 1);

            for (int j = 0; j < 6 - numberStr.length(); j++) {
                builder.append(0);
            }
            builder.append(numberStr).append(".jpg");


            file[i] = new File("background/" + builder.toString());
        }

        background.processBackground(file);


        // Test Image

        ProcessTask task = new ProcessTask(background);
        task.execute();

    }

    class ProcessTask extends SwingWorker {

        Background background;

        ProcessTask(Background bg) {
            background = bg;
        }

        @Override
        public Object doInBackground() {
            StringBuilder builder = new StringBuilder();
            for (int i = 0; i < 200; i++) {
                builder.delete(0, builder.length());
                String numberStr = Integer.toString(i + 1);

                for (int j = 0; j < 6 - numberStr.length(); j++) {
                    builder.append(0);
                }
                builder.append(numberStr).append(".jpg");

                System.out.println("Loading image... " + builder);
//                background.getSubtraction(ImageHelper.openAsGrayscale(new File("testing/" + builder)));
                panel.setImage(background.getSubtraction(ImageHelper.openAsGrayscale(new File("testing/" + builder))));
                try {
                    Thread.sleep(40);
                } catch (InterruptedException ex) {
                    ex.printStackTrace();
                    
                }
                
            }
            System.out.println("DONE");
            return null;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;




                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
